# Generated by Django 3.0.1 on 2020-02-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffreport',
            options={'verbose_name': 'StaffReport', 'verbose_name_plural': 'StaffReports'},
        ),
        migrations.AddField(
            model_name='staffreport',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffProfile'),
        ),
    ]
