# Generated by Django 3.0.1 on 2020-02-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200204_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffreport',
            old_name='staff',
            new_name='staf',
        ),
    ]
